apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: LoadBalancer
  ports:
  - name: "vote-service"
    port: 5001
    targetPort: 5001
  selector:
    app: vote
  
